# Generated by Django 4.1.4 on 2023-01-20 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stu_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_No', models.IntegerField(default=100)),
                ('Dept_no', models.IntegerField(default=100)),
                ('Salary', models.IntegerField()),
                ('Emp_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
    ]
